module.exports = {
  someSidebar: {
    AV: ["assembly", "soundboard", "lighting"],
    Adobe: ["adadmin", "newpkg", "deploypkg"],
    Classcharts: ["ccharts", "cchstudentcodes", "cchteachcodes", "cchteachperms"],
    Computers: ["imaging", "naming", "laptopsup", "pxeboot"],
    Emails: ["parents", "format", "inbox", "medhurst"],
    Google: ["gsync", "ggroups", "gadmin", "gexporting", "greports", "calsync"],
    iPads: ["dfu", "jamf", "prestage", "jamfgroups", "ipcommon", "claims"],
    Network: ["servoview"],
    Phones: ["ports", "phoneconf", "phonebugs", "phoneserver", "phonemanager", "holidays"],
    Powershell: ["scripts"],
    Printers: ["printportal", "prinsync", "printaccounts", "toners", "jamming"],
    SIMS: ["simsoverview", "simsperms", "simsttables", "simstutor"],
    Salamander: ["salsoft", "salsyncs", "sallogs", "salreps", "saltix"],
    Smoothwall: ["whitelist", "blacklist", "swreport", "smediagrp", "sgreports"],
    StaffIDs: ["idprinting"],
    Website: ["wordpressoview", "wpupload", "wpgupdate"],
    WiFi: ["ahive", "apcstatus", "ahcommon", "wiusers", "ahreports", "ahcert"],
    WindowsServer: ["ad", "gp", "switches", "servers"],
  },
};
